var R=require("../chunks/ssr/[turbopack]_runtime.js")("server/app/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ubvjr-._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0tej5c5._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0y3tlf_.js")
R.c("server/chunks/ssr/[root-of-the-server]__10ldt1g._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0g84hko._.js")
R.c("server/chunks/ssr/src_160p-yb._.js")
R.c("server/chunks/ssr/_01lsh4o._.js")
R.c("server/chunks/ssr/node_modules_lucide-react_dist_esm_1kut4qh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0p8s4lh._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/_next-internal_server_app_page_actions_0hhsz1j.js")
R.m(24466)
module.exports=R.m(24466).exports
